### ISSUE TITLE
[Issue] Statistics wrong

### ISSUE THREAD

**Issue by Spikeone** [nicymike/serflings#2]
Something... went wrong:
![image](https://user-images.githubusercontent.com/1276342/71737106-089ea780-2e53-11ea-8ff3-579202b67bfa.png)

**Comment by nicymike** [comment]
Yes, this is a known bug. I will fix this when I am going to reimplement the dialog from the original game.

**Comment by nicymike** [comment]
I found the bug: The calculation is absolutely wrong.
I also found some additional bugs, eg. the statistics are currently not beeing loaded from savegame.

All this will be fixed in the next release. I am going to validate the whole function which calculates the statistics and also the production history of goods.

**Comment by nicymike** [comment]
Will be fixed in next development version
