### ISSUE TITLE
[Issue] Clicks not registered properly

### ISSUE THREAD

**Issue by Spikeone** [nicymike/serflings#3]
Sadly left and right clicks are not registered properly. This makes it really hard to scroll or "special" click in most cases.

**Comment by nicymike** [comment]
For the special click I advise to first click the right mouse button and then add the left one. This is more stable.

I watched your network game on youtube and I think this issue is because of the lags. I assume it works correctly in singleplayer. Can you verify this?

**Comment by Spikeone** [comment]
Can confirm, it's working great when playing alone

**Comment by nicymike** [comment]
Ok, so I guess this will be fixed if I fix the lags.

**Comment by nicymike** [comment]
I optimized some parts in the current version to reduce latency. Could you please test multiplayer again to check if it is better now?

**Comment by Spikeone** [comment]
@nicymike Sadly this is not working as one would expect just yet. At least my rightclicks are sometimes not registered properly. 
This results in:
- not start scrolling when right clicking
- not stoping scrolling when releasing
- windows not opening
- geologists not being called

**Comment by nicymike** [comment]
I think I found the problem but I need some time to fix it because I have to change some internals for this.

The problem in detail:
I handle a click every time a button is released in the current tick for keyboard and game. If there is a lag because of network latency the keyboard ticks are running but the game ticks are not. This means the game will not get the released status. I need to change how inputs are handled in game tick.

**Comment by Spikeone** [comment]
Don't worry, I know that such changes require some (a lot) time :)

**Comment by nicymike** [comment]
I managed to fix this issue by separating the inputs from the ticks.
