### ISSUE TITLE
knight strength bug

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#43]
Not sure what happened here:
![image](https://user-images.githubusercontent.com/68932712/95908409-3d1e9700-0dc7-11eb-845b-23b456ad5aaa.png)
[SAVE5.zip](https://github.com/nicymike/serflings/files/5373733/SAVE5.zip)
If I load it up in the original game, it shows correct figures: 25%

**Comment by nicymike** [comment]
Found it. It is a bug that also exists in the original game but has a different outcome because of how Assembler does the calculations in the original game.

Knight motivation is calculated with the help of the amount of gold on the entire map to define the percentage of every player.
BUT: Because of a bug, the gold which is created within the castle is not beeing added to the counter of the map. If you play a map with almost no gold in the ground and if the gold of the castles is somehow destroyed (demolish of building with gold or demolish of path with a carrier carrying gold), the counter may be negative.
The original game then calculates 25% of motivation for every player while Serflings calculates more than 1000% of motivation.

I could change Serflings to mimic the original game which will also lead to 25% or I could fix the issue and count the gold created within the castle.
What do you think?

**Comment by nicymike** [comment]
As discussed in Discord, I will change the remake to mimic the original game. The calculation will be fixed to show 25%.
I will add the ability to set game rules at a future version of the remake where you are able to activate the gold fix for castles.
