### ISSUE TITLE
Workers are not created in castle to move to their house, when castle is not filled up with knights.(orig Bug?)

### ISSUE THREAD

**Issue by Wakeboardtiger** [nicymike/serflings#86]
I played from serflings to this point where i build 3 house for the bakery industry, which where not ocupied by workers, even i have the tools and population. I loaded it into the original game: No change. I added another house still no change. I need to pull down the numbers of knights left in the castle before i get more worker created. That shouldnt be the case, since i have enough population left for normal jobs!
![image](https://user-images.githubusercontent.com/68932712/219339666-18eaf7e5-2baa-47bd-8491-ff10acd25141.png)

[SAVE5.zip](https://github.com/nicymike/serflings/files/10754156/SAVE5.zip)

**Comment by nicymike** [comment]
I guess this is a bug which also exists in the original game. When the number of required knights for the castle is too low the castle tries to train a new knight. If this fails it locks the unemployed settlers into place which means they are stuck in the castle.

I will think about a fix because the lock is not needed.

Thank you for finding this bug. :)

**Comment by nicymike** [comment]
Fixed in the next development version.
